name: kinopoisk_plus
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  google_fonts: ^6.2.1
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  firebase_database: ^10.5.4
  firebase_storage: ^11.7.4
  fluttertoast: ^8.0.8
  ndialog: ^4.1.0
  intl: ^0.19.0
  image_picker: ^1.1.1
  path_provider: ^2.0.5
  google_nav_bar: ^5.0.6
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  json_serializable: ^6.7.1
  build_runner: ^2.4.8


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MontserratBold
      fonts:
        - asset: fonts/MontserratMedium.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
